cmireaderservice:
  cmi-address: address
  cmi-username: username
  cmi-password: password
  device-type: UVR16X2
  device-can-node: 1
  device-timezone: "Europe/Vienna" # Java TimeZone
  collect-interval: 60000
  api-base-url: "https://api.logreposit.com/v1/"
  api-client-retry-count: 5
  api-client-retry-initial-back-off-interval: 1200
  api-client-retry-back-off-multiplier: 1.5

logging:
  pattern:
    console: "%clr(%d{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{correlationId:-}]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC} ${LOG_LEVEL_PATTERN:%5p} ${PID: } --- [%t] [%X{correlationId:-}] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: logs/cmi-reader-service.log

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
